config/routes.rb
Rails.application.routes.draw do
  resources :light_readings
  resources :water_readings
  resources :gardens
  get 'gardens/register/:id' => 'gardens#register', :as => :register_garden
  devise_for :users
  root 'gardens#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/light_reading.rb
class LightReading < ApplicationRecord
    belongs_to :garden
end

app/controllers/light_readings_controller.rb
class LightReadingsController < ApplicationController
  skip_before_action :verify_authenticity_token
  skip_before_action :authenticate_user!
  before_action :set_light_reading, only: [:show, :edit, :update, :destroy]

  # GET /light_readings
  # GET /light_readings.json
  def index
    @light_readings = LightReading.all
    respond_to do |format|
      format.html
      format.xlsx
    end
  end

  # GET /light_readings/1
  # GET /light_readings/1.json
  def show
  end

  # GET /light_readings/new
  def new
    @light_reading = LightReading.new
  end

  # GET /light_readings/1/edit
  def edit
  end

  # POST /light_readings
  # POST /light_readings.json
  def create
    @light_reading = LightReading.new(light_reading_params)

    respond_to do |format|
      if @light_reading.save
        format.html { redirect_to @light_reading, notice: 'Light reading was successfully created.' }
        format.json { render :show, status: :created, location: @light_reading }
      else
        format.html { render :new }
        format.json { render json: @light_reading.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /light_readings/1
  # PATCH/PUT /light_readings/1.json
  def update
    respond_to do |format|
      if @light_reading.update(light_reading_params)
        format.html { redirect_to @light_reading, notice: 'Light reading was successfully updated.' }
        format.json { render :show, status: :ok, location: @light_reading }
      else
        format.html { render :edit }
        format.json { render json: @light_reading.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /light_readings/1
  # DELETE /light_readings/1.json
  def destroy
    @light_reading.destroy
    respond_to do |format|
      format.html { redirect_to light_readings_url, notice: 'Light reading was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_light_reading
      @light_reading = LightReading.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def light_reading_params
      params.require(:light_reading).permit(:node1, :node2, :node3, :node4, :node5, :node6, :node7, :node8, :temp, :garden_id)
    end
end

app/helpers/light_readings_helper.rb
module LightReadingsHelper
end

app/views/light_readings/_form.html.erb
<%= form_with(model: light_reading, local: true) do |form| %>
  <% if light_reading.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(light_reading.errors.count, "error") %> prohibited this light_reading from being saved:</h2>

      <ul>
      <% light_reading.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :node1 %>
    <%= form.number_field :node1, id: :light_reading_node1 %>
  </div>

  <div class="field">
    <%= form.label :node2 %>
    <%= form.number_field :node2, id: :light_reading_node2 %>
  </div>

  <div class="field">
    <%= form.label :node3 %>
    <%= form.number_field :node3, id: :light_reading_node3 %>
  </div>

  <div class="field">
    <%= form.label :node4 %>
    <%= form.number_field :node4, id: :light_reading_node4 %>
  </div>

  <div class="field">
    <%= form.label :node5 %>
    <%= form.number_field :node5, id: :light_reading_node5 %>
  </div>

  <div class="field">
    <%= form.label :node6 %>
    <%= form.number_field :node6, id: :light_reading_node6 %>
  </div>

  <div class="field">
    <%= form.label :node7 %>
    <%= form.number_field :node7, id: :light_reading_node7 %>
  </div>

  <div class="field">
    <%= form.label :node8 %>
    <%= form.number_field :node8, id: :light_reading_node8 %>
  </div>

  <div class="field">
    <%= form.label :temp %>
    <%= form.number_field :temp, id: :light_reading_temp %>
  </div>

  <div class="field">
    <%= form.label :garden_id %>
    <%= form.number_field :garden_id, id: :light_reading_garden_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/light_readings/edit.html.erb
<h1>Editing Light Reading</h1>

<%= render 'form', light_reading: @light_reading %>

<%= link_to 'Show', @light_reading %> |
<%= link_to 'Back', light_readings_path %>

app/views/light_readings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Light Readings</h1>

<table>
  <thead>
    <tr>
      <th>Reading at</th>
      <th>Node1</th>
      <th>Node2</th>
      <th>Node3</th>
      <th>Node4</th>
      <th>Node5</th>
      <th>Node6</th>
      <th>Node7</th>
    </tr>
  </thead>

  <tbody>
    <% @light_readings.each.reverse_each do |light_reading| %>
      <tr>
        <td><%= light_reading.created_at.in_time_zone("Central Time (US & Canada)").strftime("%m-%d-%Y %l:%M %p") %></td>
        <td><%= light_reading.node1 %></td>
        <td><%= light_reading.node2 %></td>
        <td><%= light_reading.node3 %></td>
        <td><%= light_reading.node4 %></td>
        <td><%= light_reading.node5 %></td>
        <td><%= light_reading.node6 %></td>
        <td><%= light_reading.node7 %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Export Readings to excel spreadsheet', light_readings_path(format: "xlsx"),:class => 'button' %>
<%= link_to 'Back',gardens_path,:class => 'button' %>

app/views/light_readings/new.html.erb
<h1>New Light Reading</h1>

<%= render 'form', light_reading: @light_reading %>

<%= link_to 'Back', light_readings_path %>

app/views/light_readings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Node1:</strong>
  <%= @light_reading.node1 %>
</p>

<p>
  <strong>Node2:</strong>
  <%= @light_reading.node2 %>
</p>

<p>
  <strong>Node3:</strong>
  <%= @light_reading.node3 %>
</p>

<p>
  <strong>Node4:</strong>
  <%= @light_reading.node4 %>
</p>

<p>
  <strong>Node5:</strong>
  <%= @light_reading.node5 %>
</p>

<p>
  <strong>Node6:</strong>
  <%= @light_reading.node6 %>
</p>

<p>
  <strong>Node7:</strong>
  <%= @light_reading.node7 %>
</p>

<p>
  <strong>Node8:</strong>
  <%= @light_reading.node8 %>
</p>


<p>
  <strong>Garden:</strong>
  <%= @light_reading.garden_id %>
</p>

<%= link_to 'Edit', edit_light_reading_path(@light_reading),:class => 'button' %> |
<%= link_to 'Back', light_readings_path,:class => 'button' %>