config/routes.rb
Rails.application.routes.draw do
  resources :light_readings
  resources :water_readings
  resources :gardens
  get 'gardens/register/:id' => 'gardens#register', :as => :register_garden
  devise_for :users
  root 'gardens#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/garden.rb
class Garden < ApplicationRecord
    has_many :user
    has_many :water_reading
    has_many :light_reading
end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController
  before_action :set_garden, only: [:show, :edit, :update, :destroy]

  # GET /gardens
  # GET /gardens.json
  def index
    @gardens = current_user_gardens(current_user)
    if(@gardens.size>0)
      redirect_to garden_path(@gardens.first)
    else
      @gardens=Garden.all
    end
  end
  # GET /gardens/1
  # GET /gardens/1.json
  def show
    gon.water_node1 = @garden.water_reading.last.node1
    gon.water_node2 = @garden.water_reading.last.node2
    gon.water_node3 = @garden.water_reading.last.node3
    gon.water_node4 = @garden.water_reading.last.node4
    gon.water_node5 = @garden.water_reading.last.node5
    gon.water_node6 = @garden.water_reading.last.node6
    gon.water_node7 = @garden.water_reading.last.node7
    gon.light_node1 = @garden.light_reading.last.node1
    gon.light_node2 = @garden.light_reading.last.node2
    gon.light_node3 = @garden.light_reading.last.node3
    gon.light_node4 = @garden.light_reading.last.node4
    gon.light_node5 = @garden.light_reading.last.node5
    gon.light_node6 = @garden.light_reading.last.node6
    gon.light_node7 = @garden.light_reading.last.node7
  end

  # GET /gardens/new
  def new
    @garden = Garden.new
  end

  # GET /gardens/1/edit
  def edit
  end

  # POST /gardens
  # POST /gardens.json
  def create
    @garden = Garden.new(garden_params)
    respond_to do |format|
      if @garden.save
        current_user.update_column(:garden_name, @garden.name)
        puts current_user.garden_name
        format.html { redirect_to @garden, notice: 'Garden was successfully created.' }
        format.json { render :show, status: :created, location: @garden }
      else
        format.html { render :new }
        format.json { render json: @garden.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gardens/1
  # PATCH/PUT /gardens/1.json
  def update
    respond_to do |format|
      if @garden.update(garden_params)
        format.html { redirect_to @garden, notice: 'Garden was successfully updated.' }
        format.json { render :show, status: :ok, location: @garden }
      else
        format.html { render :edit }
        format.json { render json: @garden.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gardens/1
  # DELETE /gardens/1.json
  def destroy
    @garden.destroy
    respond_to do |format|
      format.html { redirect_to gardens_url, notice: 'Garden was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def register
    @garden = Garden.find(params[:id])
    current_user.update_column(:garden_name, @garden.name)
    flash[:notice] = current_user.garden_name
    redirect_to root_path
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_garden
      @garden = Garden.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def garden_params
      params.require(:garden).permit(:name, :password)
    end
    def current_user_gardens(user)
      Garden.where("gardens.name = ?",user.garden_name)
    end

end

app/helpers/gardens_helper.rb
module GardensHelper
end

app/views/gardens/_form.html.erb
<%= form_with(model: garden, local: true) do |form| %>
  <% if garden.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(garden.errors.count, "error") %> prohibited this garden from being saved:</h2>

      <ul>
      <% garden.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :garden_name %>
  </div>

  <div class="field">
    <%= form.label :password2 %>
    <%= form.text_field :password, id: :garden_password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/gardens/edit.html.erb
<h1>Editing Garden</h1>

<%= render 'form', garden: @garden %>

<%= link_to 'Show', @garden %> |
<%= link_to 'Back', gardens_path %>

app/views/gardens/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gardens</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gardens.each do |garden| %>
      <tr>
        <td><%= garden.name %></td>
        <td> <%= garden.id %></td>
        <td><%= link_to 'Register a garden',register_garden_path(@user,:id => garden.id) %></td>
        <td><%= link_to 'Remove Garden', garden, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Create Garden', new_garden_path %>

app/views/gardens/new.html.erb
<h1>New Garden</h1>

<%= render 'form', garden: @garden %>

<%= link_to 'Back', gardens_path %>

app/views/gardens/register.html.erb
<h1>Register Garden</h1>


<%= link_to 'Back', gardens_path %>

app/views/gardens/show.html.erb
<%=include_gon %>;

    <div id="floating-panel"</div>
      <button onclick="toggleHeatmap()">Toggle Heatmap</button>
      <button onclick="changeRadius()">Change radius</button>
      <button onclick="changeOpacity()">Change opacity</button>
        <script>changeGradient();</script>
    </div>
    <div id="map"></div>
<tr><%= link_to 'View All Water Readings', water_readings_path,:class => 'button' %></tr>
<%= link_to 'View All Light Readings', light_readings_path,:class => 'button' %>
    <div id="floating-panel">
      <button onclick="toggleHeatmap()">Toggle Heatmap</button>
      <button onclick="changeRadius()">Change radius</button>
      <button onclick="changeOpacity()">Change opacity</button>
        <script>changeGradient();</script>
    </div>
    <div id="map"></div>
    
    <script>

      // This example requires the Visualization library. Include the libraries=visualization
      // parameter when you first load the API. For example:
      // <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=visualization">

      var map, heatmap;
      var firstData = true;

      function initMap() {
              var waterData = [
              {location: new google.maps.LatLng(41.663969, -91.580529), weight: gon.water_node1}, 
              {location: new google.maps.LatLng(41.663844, -91.580728), weight: gon.water_node2},  
              {location: new google.maps.LatLng(41.663896, -91.580728), weight: gon.water_node3},
              {location: new google.maps.LatLng(41.663873, -91.580867), weight: gon.water_node4}, 
              {location: new google.maps.LatLng(41.663971, -91.580535), weight: gon.water_node5},  
              {location: new google.maps.LatLng(41.663995, -91.580535), weight: gon.water_node6}, 
              {location: new google.maps.LatLng(41.663975, -91.580774), weight: gon.water_node7}
        ]
      var lightData = [
              {location: new google.maps.LatLng(41.663969, -91.580529), weight: gon.light_node1}, 
              {location: new google.maps.LatLng(41.663844, -91.580728), weight: gon.light_node2},  
              {location: new google.maps.LatLng(41.663896, -91.580728), weight: gon.light_node3},
              {location: new google.maps.LatLng(41.663873, -91.580867), weight: gon.light_node4}, 
              {location: new google.maps.LatLng(41.663971, -91.580535), weight: gon.light_node5},  
              {location: new google.maps.LatLng(41.663995, -91.580535), weight: gon.light_node6}, 
              {location: new google.maps.LatLng(41.663975, -91.580774), weight: gon.light_node7}
        ]
        map = new google.maps.Map(document.getElementById('map'), {
          zoom: 20,
          center: {lat: 41.663934, lng: -91.580702}, 
          mapTypeId: 'satellite'
        });
        waterArray = new google.maps.MVCArray(waterData)
        lightArray = new google.maps.MVCArray(lightData)
        heatmap = new google.maps.visualization.HeatmapLayer({
          data: waterArray,
          map: map
        });
      }

      function toggleHeatmap() {
        if(firstData){
          heatmap.setData(lightArray);
          firstData = false;
        }else{
          heatmap.setData(waterArray);
          firstData=true;
        }

      function changeGradient() {
        var gradient = [
          'rgba(0, 255, 255, 0)',
          'rgba(0, 255, 255, 1)',
          'rgba(0, 191, 255, 1)',
          'rgba(0, 127, 255, 1)',
          'rgba(0, 63, 255, 1)',
          'rgba(0, 0, 255, 1)',
          'rgba(0, 0, 223, 1)',
          'rgba(0, 0, 191, 1)',
          'rgba(0, 0, 159, 1)',
          'rgba(0, 0, 127, 1)',
          'rgba(63, 0, 91, 1)',
          'rgba(127, 0, 63, 1)',
          'rgba(191, 0, 31, 1)',
          'rgba(255, 0, 0, 1)'
        ]
        heatmap.set('gradient', heatmap.get('gradient') ? null : gradient);
      }

      function changeRadius() {
        heatmap.set('radius', heatmap.get('radius') ? null : 50);
      }

      function changeOpacity() {
        heatmap.set('opacity', heatmap.get('opacity') ? null : 0.2);
      }
}
      // Heatmap data: 8 Points
    </script>
    <script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCBmeSHfe_LRphiwgEiP5CVF4ddctpEvMk &libraries=visualization&callback=initMap">
    </script>