config/routes.rb
Rails.application.routes.draw do
  resources :light_readings
  resources :water_readings
  resources :gardens
  get 'gardens/register/:id' => 'gardens#register', :as => :register_garden
  devise_for :users
  root 'gardens#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/water_reading.rb
class WaterReading < ApplicationRecord
    belongs_to :garden
end

app/controllers/water_readings_controller.rb
class WaterReadingsController < ApplicationController
  skip_before_action :verify_authenticity_token
  skip_before_action :authenticate_user!
  before_action :set_water_reading, only: [:show, :edit, :update, :destroy]

  # GET /water_readings
  # GET /water_readings.json
  def index
    @water_readings = WaterReading.all
    respond_to do |format|
      format.html
      format.xlsx
    end
  end

  # GET /water_readings/1
  # GET /water_readings/1.json
  def show
  end

  # GET /water_readings/new
  def new
    @water_reading = WaterReading.new
  end

  # GET /water_readings/1/edit
  def edit
  end

  # POST /water_readings
  # POST /water_readings.json
  def create
    @water_reading = WaterReading.new(water_reading_params)
    respond_to do |format|
      if @water_reading.save
        format.html { redirect_to @water_reading, notice: 'Water reading was successfully created.' }
        format.json { render :json => @water_reading, status: :created, location: @water_reading }
      else
        format.html { render :new }
        format.json { render json: @water_reading.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /water_readings/1
  # PATCH/PUT /water_readings/1.json
  def update
    respond_to do |format|
      if @water_reading.update(water_reading_params)
        format.html { redirect_to @water_reading, notice: 'Water reading was successfully updated.' }
        format.json { render :show, status: :ok, location: @water_reading }
      else
        format.html { render :edit }
        format.json { render json: @water_reading.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /water_readings/1
  # DELETE /water_readings/1.json
  def destroy
    @water_reading.destroy
    respond_to do |format|
      format.html { redirect_to water_readings_url, notice: 'Water reading was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_water_reading
      @water_reading = WaterReading.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def water_reading_params
      params.require(:water_reading).permit(:node1, :node2, :node3, :node4, :node5, :node6, :node7, :node8 ,:garden_id)
    end
end

app/helpers/water_readings_helper.rb
module WaterReadingsHelper
end

app/views/water_readings/_form.html.erb
<%= form_with(model: water_reading, local: true) do |form| %>
  <% if water_reading.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(water_reading.errors.count, "error") %> prohibited this water_reading from being saved:</h2>

      <ul>
      <% water_reading.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :node1 %>
    <%= form.number_field :node1, id: :water_reading_node1 %>
  </div>

  <div class="field">
    <%= form.label :node2 %>
    <%= form.number_field :node2, id: :water_reading_node2 %>
  </div>

  <div class="field">
    <%= form.label :node3 %>
    <%= form.number_field :node3, id: :water_reading_node3 %>
  </div>

  <div class="field">
    <%= form.label :node4 %>
    <%= form.number_field :node4, id: :water_reading_node4 %>
  </div>

  <div class="field">
    <%= form.label :node5 %>
    <%= form.number_field :node5, id: :water_reading_node5 %>
  </div>

  <div class="field">
    <%= form.label :node6 %>
    <%= form.number_field :node6, id: :water_reading_node6 %>
  </div>

  <div class="field">
    <%= form.label :node7 %>
    <%= form.number_field :node7, id: :water_reading_node7 %>
  </div>

  <div class="field">
    <%= form.label :node8 %>
    <%= form.number_field :node8, id: :water_reading_node8 %>
  </div>
  <div class="field">
    <%= form.label :garden_id %>
    <%= form.number_field :garden_id, id: :water_reading_garden_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/water_readings/edit.html.erb
<h1>Editing Water Reading</h1>

<%= render 'form', water_reading: @water_reading %>

<%= link_to 'Show', @water_reading %> |
<%= link_to 'Back', water_readings_path %>

app/views/water_readings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Water Readings</h1>

<table>
  <thead>
    <tr>
      <th>Reading at</th>
      <th>Node1</th>
      <th>Node2</th>
      <th>Node3</th>
      <th>Node4</th>
      <th>Node5</th>
      <th>Node6</th>
      <th>Node7</th>
    </tr>
  </thead>

  <tbody>
    <% @water_readings.each.reverse_each do |water_reading| %>
      <tr>
        <td><%= water_reading.created_at.in_time_zone("Central Time (US & Canada)").strftime("%m-%d-%Y %l:%M %p") %></td>
        <td><%= water_reading.node1 %></td>
        <td><%= water_reading.node2 %></td>
        <td><%= water_reading.node3 %></td>
        <td><%= water_reading.node4 %></td>
        <td><%= water_reading.node5 %></td>
        <td><%= water_reading.node6 %></td>
        <td><%= water_reading.node7 %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Export Readings to excel spreadsheet', water_readings_path(format: "xlsx"),:class => 'button' %>
<%= link_to 'Back',gardens_path,:class => 'button' %>

app/views/water_readings/map.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Heatmaps</title>
    <style>
      /* Always set the map height explicitly to define the size of the div
       * element that contains the map. */
      #map {
        height: 100%;
      }
      /* Optional: Makes the sample page fill the window. */
      html, body {
        height: 60%;
        width: 60%;
        margin: 0;
        padding: 10%;
      }
      #floating-panel {
        position: absolute;
        top: 10px;
        left: 25%;
        z-index: 5;
        background-color: #fff;
        padding: 5px;
        border: 1px solid #999;
        text-align: center;
        font-family: 'Roboto','sans-serif';
        line-height: 30px;
        padding-left: 10px;
      }
      #floating-panel {
        background-color: #fff;
        border: 1px solid #999;
        left: 25%;
        padding: 5px;
        position: absolute;
        top: 10px;
        z-index: 5;
      }
    </style>
  
    </head>
    
  <body>
      
    <div id="floating-panel">
      <button onclick="toggleHeatmap()">Toggle Heatmap</button>
      <button onclick="changeRadius()">Change radius</button>
      <button onclick="changeOpacity()">Change opacity</button>
        <script>changeGradient();</script>
    </div>
    <div id="map"></div>
    
    <script>

      // This example requires the Visualization library. Include the libraries=visualization
      // parameter when you first load the API. For example:
      // <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=visualization">

      var map, heatmap;

      function initMap() {
        map = new google.maps.Map(document.getElementById('map'), {
          zoom: 20,
          center: {lat: 41.663934, lng: -91.580702}, 
          mapTypeId: 'satellite'
        });

        heatmap = new google.maps.visualization.HeatmapLayer({
          data: getPoints(),
          map: map
        });
      }

      function toggleHeatmap() {
        heatmap.setMap(heatmap.getMap() ? null : map);
      }

      function changeGradient() {
        var gradient = [
          'rgba(0, 255, 255, 0)',
          'rgba(0, 255, 255, 1)',
          'rgba(0, 191, 255, 1)',
          'rgba(0, 127, 255, 1)',
          'rgba(0, 63, 255, 1)',
          'rgba(0, 0, 255, 1)',
          'rgba(0, 0, 223, 1)',
          'rgba(0, 0, 191, 1)',
          'rgba(0, 0, 159, 1)',
          'rgba(0, 0, 127, 1)',
          'rgba(63, 0, 91, 1)',
          'rgba(127, 0, 63, 1)',
          'rgba(191, 0, 31, 1)',
          'rgba(255, 0, 0, 1)'
        ]
        heatmap.set('gradient', heatmap.get('gradient') ? null : gradient);
      }
      changeGrandient();

      function changeRadius() {
        heatmap.set('radius', heatmap.get('radius') ? null : 50);
      }

      function changeOpacity() {
        heatmap.set('opacity', heatmap.get('opacity') ? null : 0.2);
      }

      // Heatmap data: 8 Points
      function getPoints() {
        return [
            {location: new google.maps.LatLng(41.663978, -91.580580), weight: 40}, 
            {location: new google.maps.LatLng(41.663992, -91.580635), weight: 30},  
            {location: new google.maps.LatLng(41.663999, -91.580807), weight: 35}, 
            {location: new google.maps.LatLng(41.663987, -91.580862), weight: 40}, 
            {location: new google.maps.LatLng(41.663895, -91.580858), weight: 32},  
            {location: new google.maps.LatLng(41.663900, -91.580804), weight: 36}, 
            {location: new google.maps.LatLng(41.663897, -91.580690), weight: 41},
            {location: new google.maps.LatLng(41.663882, -91.580580), weight: 50},  
        ];
      }
    </script>
    <script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCBmeSHfe_LRphiwgEiP5CVF4ddctpEvMk &libraries=visualization&callback=initMap">
    </script>
      
  </body>
</html>

app/views/water_readings/new.html.erb
<h1>New Water Reading</h1>

<%= render 'form', water_reading: @water_reading %>

<%= link_to 'Back', water_readings_path %>

app/views/water_readings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Node1:</strong>
  <%= @water_reading.node1 %>
</p>

<p>
  <strong>Node2:</strong>
  <%= @water_reading.node2 %>
</p>

<p>
  <strong>Node3:</strong>
  <%= @water_reading.node3 %>
</p>

<p>
  <strong>Node4:</strong>
  <%= @water_reading.node4 %>
</p>

<p>
  <strong>Node5:</strong>
  <%= @water_reading.node5 %>
</p>

<p>
  <strong>Node6:</strong>
  <%= @water_reading.node6 %>
</p>

<p>
  <strong>Node7:</strong>
  <%= @water_reading.node7 %>
</p>

<p>
  <strong>Node8:</strong>
  <%= @water_reading.node8 %>
</p>
<p>
  <strong>Time:</strong>
  <%= @water_reading.created_at %>
</p>

<%= link_to 'Edit', edit_water_reading_path(@water_reading) %> |
<%= link_to 'Back', water_readings_path %>